package com.ordevia.aidev.workitem.domain;

public enum WorkItemStatus {
    NEW,
    PLANNING,
    WAITING_FOR_USER_INPUT,
    READY_FOR_PLANNING_REVIEW,
    PLANNING_HUMAN_REQUIRED,
    READY_FOR_DOMAIN_VALIDATION,
    DOMAIN_VALIDATING,
    DOMAIN_HUMAN_REQUIRED,
    READY_FOR_ARCHITECTURE,
    ARCHITECTING,
    ARCHITECTURE_HUMAN_REQUIRED,
    READY_FOR_DEVELOPMENT,
    IMPLEMENTING,
    INTEGRATING,
    QA_VALIDATING,
    REVIEWING,
    SECURITY_REVIEWING,
    CHANGES_REQUESTED,
    READY_FOR_HUMAN_REVIEW,
    RELEASE_PREPARING,
    RELEASE_HUMAN_REQUIRED,
    DONE,
    FAILED
}
