package com.ordevia.aidev.workitem.domain;

public enum WorkItemStatus {
    NEW,
    PLANNING,
    WAITING_FOR_USER_INPUT,
    READY_FOR_PLANNING_REVIEW,
    PLANNING_HUMAN_REQUIRED,
    READY_FOR_DEVELOPMENT,
    IMPLEMENTING,
    REVIEWING,
    CHANGES_REQUESTED,
    READY_FOR_HUMAN_REVIEW,
    DONE,
    FAILED
}
